services:

  psql_db_training_app:
    image: postgres:16-alpine3.20
    container_name: psql_db_training_app
    ports:
      - 5432:5432
    volumes:
      - psql_db_training_app:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - training_app
    environment:
      - POSTGRES_DB=training_app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mysecurepassword

  api_training_app:
    container_name: api_training_app
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - api_training_app:/usr/src/app/
    networks:
      - training_app
    depends_on:
      - psql_db_training_app
    environment:
      - PORT=3001
      - DB_HOST=psql_db_training_app
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=mysecurepassword
      - DB_DBNAME=training_app  
      - AUTH0_DOMAIN=your-auth0-domain
      - AUTH0_AUDIENCE=your-auth0-audience
      - FRONT_URL=http://localhost:3000
      - BASEURL=http://localhost:3001

  front_training_app:
    container_name: front_training_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - training_app
    depends_on:
      - api_training_app
    environment:
      - API_SERVER=api_training_app
      - DOMAIN_AUTH0=https://your-auth0-domain.com
      - CLIENT_ID_AUTH0=your-client-id
      - REDIRECT_URL=front_training_app
      - AUDIENCE=your-auth0-audience
      - AUTH0_EMAIL=your-email@example.com
      - AUTH0_PASSWORD=your-password
      - DIET_AUTH0_ENDPOINT=https://your-diet-auth0-endpoint.com

volumes:
  api_training_app:
  psql_db_training_app:

networks:
  training_app:
    driver: bridge
    