name: Build frontend
on:
    workflow_dispatch:
    push:
      branches:
        - main
      paths:
        - 'frontend/**'
    pull_request:
      branches:
        - main
      paths:
        - 'frontend/**'
jobs:
  get-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3