name: Build and Push Docker Image to OCIR

on:
    workflow_dispatch: 
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_COMPARTMENT_OCID: ${{ secrets.OCI_COMPARTMENT_OCID }}
      FRONT_REPO_NAME: front-training-app
      SERVER_REPO_NAME: server-training-app  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker 
        uses: docker/setup-buildx-action@v3

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Oracle Cloud Infrastructure Registry (OCIR)
        uses: oracle-actions/login-ocir@v1.3.0
        id: login-ocir
        with:
          auth-token: ${{ secrets.OCI_AUTH_TOKEN }}
          region: ${{ secrets.OCI_CLI_REGION }}
          tenancy: ${{ secrets.OCI_CLI_TENANCY }}

      - name: Get or create OCIR server repository
        id: get-ocir-repository-server
        uses: oracle-actions/get-ocir-repository@v1
        with:
          compartment-ocid: ${{ secrets.OCI_COMPARTMENT_OCID }}
          repository-name: ${{ env.SERVER_REPO_NAME }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
            context: ./backend
            file: ./backend/Dockerfile
            push: true
            tags: |
              ${{ steps.get-ocir-repository-server.outputs.repository_uri }}:${{ env.SHORT_SHA }}   
      - name: Get or create OCIR frontend repository
        id: get-ocir-repository-frontend
        uses: oracle-actions/get-ocir-repository@v1
        with:
          compartment-ocid: ${{ secrets.OCI_COMPARTMENT_OCID }}
          repository-name: ${{ env.FRONT_REPO_NAME}}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
            context: ./frontend
            file: ./frontend/Dockerfile
            push: true
            tags: |
              ${{ steps.get-ocir-repository-frontend.outputs.repository_uri }}:${{ env.SHORT_SHA }}   

   
