name: run test
on:
    workflow_dispatch:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
           username: ${{ vars.DOCKERHUB_USER }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       # Run Docker Compose to execute tests
      - name: Run tests with Docker Compose
        run: |
           docker compose -f docker-compose.testing.yml up --abort-on-container-exit --remove-orphans
           docker compose -f docker-compose.testing.yml down --volumes